/* GAME */
export const LOCAL_STATS = 'LOCAL_STATS';


/* AWS COGNITO */
export const CURRENT_COGNITO_SESSION = 'CURRENT_COGNITO_SESSION';
export const COGNITO_ID = 'COGNITO_ID'; 
export const IS_LOGGED_IN = 'IS_LOGGED_IN';
export const AWS_CREDENTIALS = 'AWS_CREDENTIALS';
export const COGNITO_USER_PROFILE = 'COGNITO_USER_PROFILE';
export const TOKEN_STORAGE = 'TOKEN_STORAGE';
