/* Activities */
export const SET_ACTIVE_ACTIVITY = 'SET_ACTIVE_ACTIVITY';
export const SET_ACTIVE_SEGMENT = 'SET_ACTIVE_SEGMENT';
export const UPDATE_ACTIVITIES_LIST = 'UPDATE_ACTIVITIES_LIST';

/* Analytics */
export const TRACK_NAVIGATION = 'TRACK_NAVIGATION';
export const TRACK_USER_BEHAVIOUR = 'TRACK_USER_BEHAVIOUR';
export const IDENTIFY_SEGMENT_USER = 'IDENTIFY_SEGMENT_USER';



/* Stats */
export const UPDATE_STATS = 'UPDATE_STATS';
export const SET_DISPLAY_STATS = 'SET_DISPLAY_STATS';
export const UPDATE_LOCAL_STATS = 'UPDATE_LOCAL_STATS';



/* Goals */
export const TOGGLE_DAILY_GOALS_DISPLAY = 'TOGGLE_DAILY_GOALS_DISPLAY';


/* User */
export const TOGGLE_LOCAL_GAME_MODE = 'TOGGLE_LOCAL_GAME_MODE';


/* Auth */
export const SAVE_COGNITO_PROFILE = 'SAVE_COGNITO_PROFILE';
export const UPDATE_OAUTH_TOKENS = 'UPDATE_OAUTH_TOKENS';
